//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerNetApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public int MovieOrderId { get; set; }
        public int MovieId { get; set; }
        public int Qty { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual MovieOrder MovieOrder { get; set; }
    }
}
